### ISSUE TITLE
Preparación del entorno Firebase

### ISSUE THREAD

**Issue by jonathancede** [MiguelPerezMartinez/apollofy-music-project#29]
Requerimientos:
- Estructura backend creada.

Objetivos:
- [x] Preparación del entorno en el cliente.
- [x] Preparación del entorno en el server.
- [x] Implementar High Order Component.
- [x] Implementar componente Redux para la autorización.

Finalización:
- Firebase conectado.

**Comment by MarcSola** [comment]
Added two HOCs. One (withAuth) checks if you have authorization and redirects you to Login page if you don't or redirects you to the selected page if you are authorized. This Hoc is only applied to pages which we need to have authorization to access. 

The other one (withoutAuth) checks if you don't have authorization and if that is the case, then it will only allow you to access the pages Register, Login and ResetPassword. Otherwise it won't allow you access to the previous mentioned pages, but will grant you access to the rest of the pages. This hoc is only used on the pages Register, Login and ResetPassword.
